### ISSUE TITLE
Inform7 is now under the free software Artistic-2.0 license; current release is old

### ISSUE THREAD

**Issue by leaf-node** [flathub/com.inform7.IDE#12]
Although I haven't checked its dependencies, the latest upstream code releases appear to be no longer proprietary. Perhaps the "Proprietary" license marker can be removed from the package?

The version on Flathub is marked as being 7 years old, but maybe Flahtub could base off of the the Flatpak built by them less than a year ago (haven't found the Flatpak build file yet):

https://github.com/ganelson/inform/releases/tag/v10.1.2

**Comment by ptomato** [comment]
The Flatpak build file is here: https://github.com/flathub/com.inform7.IDE/blob/master/com.inform7.IDE.yml As far as I know, that is the version that's available for installation from Flathub.

Good catch that we should update the license, that lives here: https://github.com/ptomato/inform7-ide/blob/main/com.inform7.IDE.appdata.xml

**Comment by ptomato** [comment]
Fixed by ptomato/inform7-ide#33, will be pulled in the next time we release the app to Flathub.
