### ISSUE TITLE
Can't set GTK_THEME through Flatseal

### ISSUE THREAD

**Issue by nullbasis** [flathub/com.inform7.IDE#7]
Thanks for the recent update! It's making editing a lot easier for me.

I didn't report this problem before because I wanted to see if it would go away when you updated, but alas it has not. Using [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal), I can change the theme that other Flatpak apps open in, but it doesn't work for Inform7. I usually use a dark theme for my everyday computering, but something about the dark theme in Inform just makes it hard for me to focus, so I'd like to change it so Inform opens in a light theme.

Not sure why this weird, idiosyncratic issue is happening. Flatseal can change Inform's other permissions (that I've tried), and Inform respects my system theme, but I can't use Flatseal to change the theme it opens in? I don't get it.

**Comment by ptomato** [comment]
Hi, sorry for the delay in replying — the current version of Inform uses GTK 2 which had only 2000s-era support for themes and didn't allow selecting a theme other than the system theme, so the Flatseal setting has no effect. Soon I hope to publish the upgrade using GTK 3 to Flathub, please look out for it! (Or if you are comfortable compiling things yourself, I could use some help testing.)

**Comment by nullbasis** [comment]
I looked at the GTK3 branch, but I have no clue where to begin compiling code, sorry :(

**Comment by ptomato** [comment]
I have just made a new push to that branch and what might work for you is to get [this file](https://github.com/ptomato/gnome-inform7/blob/gtk3/build-aux/com.inform7.IDE.yml) and run `flatpak-builder _build --force-clean --install com.inform7.IDE.yml` in a terminal. No guarantees though :smile:
