### ISSUE TITLE
Can not reinstall Inform7

### ISSUE THREAD

**Issue by alexsincai** [flathub/com.inform7.IDE#8]
I tried to reinstall Inform7, but keep getting the following error:

```
$ sudo flatpak install inform7 --reinstall
Looking for matches…
Found similar ref(s) for ‘inform7’ in remote ‘flathub’ (system).
Use this remote? [Y/n]: y
Found ref ‘app/com.inform7.IDE/x86_64/stable’ in remote ‘flathub’ (system).
Use this ref? [Y/n]: y

com.inform7.IDE permissions:
    ipc   pulseaudio   x11   file access [1]

    [1] xdg-documents, ~/Inform:create


        ID                      Branch         Op         Remote          Download
 1. [✗] com.inform7.IDE         stable         i          flathub         1,0 kB / 26,2 MB

Error: While trying to checkout ac7bc58ac99dc6a352eae30ce43fb81413f3fc3818a5b671e59de4cc9b2e2d48 into /var/lib/flatpak/app/com.inform7.IDE/x86_64/stable/.ac7bc58ac99dc6a352eae30ce43fb81413f3fc3818a5b671e59de4cc9b2e2d48-ZZBTF1: Opening content object 63c94c0512053315655f18f4ea8ffdd58191f4743f6beb8734f759706a0cf930: Couldn't find file object '63c94c0512053315655f18f4ea8ffdd58191f4743f6beb8734f759706a0cf930'
error: Failed to install com.inform7.IDE: While trying to checkout ac7bc58ac99dc6a352eae30ce43fb81413f3fc3818a5b671e59de4cc9b2e2d48 into /var/lib/flatpak/app/com.inform7.IDE/x86_64/stable/.ac7bc58ac99dc6a352eae30ce43fb81413f3fc3818a5b671e59de4cc9b2e2d48-ZZBTF1: Opening content object 63c94c0512053315655f18f4ea8ffdd58191f4743f6beb8734f759706a0cf930: Couldn't find file object '63c94c0512053315655f18f4ea8ffdd58191f4743f6beb8734f759706a0cf930'
```

Any ideas on how to reinstall it?

Thank you

**Comment by ptomato** [comment]
I've never seen this error before, but it looks like a corrupted installation, maybe a download got interrupted at some point. Googling `Flatpak "couldn't find file object"` brought me to this: https://github.com/flatpak/flatpak/issues/4116
Maybe some of the suggestions there will help you?

**Comment by alexsincai** [comment]
Hi (and Happy New Year!)

Alas, even after following all the steps specified there, I still get the same error :/

**Comment by ptomato** [comment]
Oh no! If the suggestions for repairing it there didn't work, maybe try uninstalling it before reinstalling it, if you haven't already? Otherwise I'm not really an expert on corrupted installations, maybe you could try opening an issue in flatpak/flatpak to ask for help?

**Comment by alexsincai** [comment]
Yeah, eventually I got it to work -- by completely uninstalling and then reinstalling flatpak. Good news is, now Inform7 works :)

Thank you very much for your help!
